-- Analytical Context: An AI infrastructure researcher wants to profile how developers are
-- compiling, quantizing, and deploying open-weights models in 2025.
-- Model titles on Hacker News contain incredibly dense, regular, yet variable string layouts
-- (e.g., DeepSeek-R1-Distill-Qwen-14B-GGUF, Llama-3.3-70B-Instruct, Qwen2.5-Coder-32B).
-- Variant: 64 wildcard pattern(s)
SELECT
    CASE
        WHEN title LIKE '%DeepSeek%R_%Distill%_B%' THEN 'DeepSeek Distilled Architecture'
        WHEN title LIKE '%DeepSeek%R_%__B%' THEN 'DeepSeek Full-Scale Reasoner (671B)'
        WHEN title LIKE '%DeepSeek%V_%__B%' THEN 'DeepSeek V-Series Base Tier'
        WHEN title LIKE '%Llama_3._%_B%GGUF%' OR title LIKE '%Llama_3._%_B%_q_%' THEN 'Llama 3.x Edge Quantized (GGUF/AWQ)'
        WHEN title LIKE '%Llama_3._%_B%Instruct%' THEN 'Llama 3.x Production Instruct'
        WHEN title LIKE '%Llama_4_%_B%Instruct%' THEN 'Llama 4 Next-Gen Inline'
        WHEN title LIKE '%Qwen_2._%Coder%_B%' THEN 'Qwen 2.5 Coder Specialized'
        WHEN title LIKE '%Qwen_2._%_B%Instruct%' THEN 'Qwen 2.5 Core Instruct'
        WHEN title LIKE '%Mistral%7B%Instruct%' THEN 'Mistral 7B Instruct Variants'
        WHEN title LIKE '%Mixtral%_x%B%Instruct%' THEN 'Mistral Mixtral MoE Architecture'
        WHEN title LIKE '%Phi-_% %B%Instruct%' THEN 'Phi-3 / Phi-4 Microsoft Edge Models'
        WHEN title LIKE '%Gemma%_B%Instruct%' THEN 'Gemma 2 / 3 Google Open Models'
        WHEN title LIKE '%Command-R%_B%' THEN 'Command-R Cohere Production'
        WHEN title LIKE '%Yi-__%B%Chat%' THEN 'Yi Large Series (01.AI)'
        WHEN title LIKE '%Falcon%_B%Instruct%' THEN 'Falcon RefinedWeb Models'
        WHEN title LIKE '%MPT%_B%Instruct%' THEN 'MPT MosaicML Architecture'
        WHEN title LIKE '%StarCoder%_B%' THEN 'StarCoder Code-Specialised'
        WHEN title LIKE '%CodeLlama%_B%Instruct%' THEN 'CodeLlama Code Instruct'
        WHEN title LIKE '%vicuna%__%b%' THEN 'Vicuna LMSYS Fine-Tune'
        WHEN title LIKE '%WizardLM%_B%' THEN 'WizardLM Evol-Instruct Series'
        WHEN title LIKE '%Orca%__%B%' THEN 'Orca / Orca-2 Microsoft Research'
        WHEN title LIKE '%alpaca%__%b%' THEN 'Alpaca Stanford Fine-Tune'
        WHEN title LIKE '%OpenHermes%_B%' THEN 'OpenHermes Teknium Series'
        WHEN title LIKE '%neural-chat%__%b%' THEN 'Neural-Chat Intel Optimised'
        WHEN title LIKE '%Zephyr%_B%' THEN 'Zephyr Beta / Gemma Alignment'
        WHEN title LIKE '%SOLAR%__%B%' THEN 'SOLAR Upstage 10.7B'
        WHEN title LIKE '%Nous-Hermes%_B%' THEN 'Nous-Hermes Fine-Tune Series'
        WHEN title LIKE '%BioMed%_B%' THEN 'BioMedLM / BioMistral Domain'
        WHEN title LIKE '%Meditron%__%B%' THEN 'Meditron Medical Domain'
        WHEN title LIKE '%Platypus%_B%' THEN 'Platypus Reasoning Fine-Tune'
        WHEN title LIKE '%dolly%__%b%' THEN 'Dolly Databricks Instruct'
        WHEN title LIKE '%StableLM%_B%' THEN 'StableLM Stability AI'
        WHEN title LIKE '%RedPajama%_B%' THEN 'RedPajama Together AI'
        WHEN title LIKE '%OpenLLaMA%_B%' THEN 'OpenLLaMA Open Reproduction'
        WHEN title LIKE '%TinyLlama%_B%' THEN 'TinyLlama Compact Edge'
        WHEN title LIKE '%phi-2%' THEN 'Phi-2 Small Language Model'
        WHEN title LIKE '%Mistral-NeMo%_B%' THEN 'Mistral NeMo Nvidia Collab'
        WHEN title LIKE '%Qwen1.5%_B%Instruct%' THEN 'Qwen 1.5 Legacy Instruct'
        WHEN title LIKE '%InternLM%__%B%' THEN 'InternLM Shanghai AI Lab'
        WHEN title LIKE '%Baichuan%__%B%' THEN 'Baichuan Chinese LLM'
        WHEN title LIKE '%ChatGLM%__%B%' THEN 'ChatGLM Tsinghua Series'
        WHEN title LIKE '%Aquila%__%B%' THEN 'Aquila BAAI Chinese Model'
        WHEN title LIKE '%bloom%__%b%' THEN 'BLOOM BigScience Multilingual'
        WHEN title LIKE '%OPT%__%B%' THEN 'OPT Meta Legacy Open'
        WHEN title LIKE '%GPT-J%_B%' THEN 'GPT-J / GPT-NeoX EleutherAI'
        WHEN title LIKE '%pythia%__%b%' THEN 'Pythia EleutherAI Scaling'
        WHEN title LIKE '%CausalLM%_B%' THEN 'CausalLM Generic Base'
        WHEN title LIKE '%DeepSeek%Coder%V_%_B%Instruct%' THEN 'DeepSeek-Coder V2 Instruct'
        WHEN title LIKE '%Llama_3._%_B%Q4%' THEN 'Llama 3.x GGUF Q4 Quant'
        WHEN title LIKE '%Llama_3._%_B%Q8%' THEN 'Llama 3.x GGUF Q8 Quant'
        WHEN title LIKE '%Qwen_2._%Math%_B%' THEN 'Qwen 2.5 Math Specialised'
        WHEN title LIKE '%Qwen_2._%VL%_B%' THEN 'Qwen 2.5 VL Vision-Language'
        WHEN title LIKE '%MiniCPM%_B%' THEN 'MiniCPM Compact CPM Series'
        WHEN title LIKE '%SmolLM%_B%' THEN 'SmolLM HuggingFace Tiny'
        WHEN title LIKE '%Jamba%_B%' THEN 'Jamba Mamba Hybrid SSM'
        WHEN title LIKE '%RWKV%__%B%' THEN 'RWKV RNN-LM Series'
        WHEN title LIKE '%mamba%__%b%' THEN 'Mamba State Space Model'
        WHEN title LIKE '%granite%__%b%instruct%' THEN 'Granite IBM Instruct'
        WHEN title LIKE '%Mistral-Large%_B%' THEN 'Mistral Large / Medium Tier'
        WHEN title LIKE '%DeepSeek%V__%_B%' THEN 'DeepSeek-V3 / V4 Latest'
        WHEN title LIKE '%Llama_3.3%_B%' THEN 'Llama 3.3 Specific Release'
        WHEN title LIKE '%Qwen3%_B%' THEN 'Qwen3 Next-Generation Series'
        WHEN title LIKE '%Gemma_3%_B%Instruct%' THEN 'Gemma 3 Latest Google Release'
        WHEN title LIKE '%Llama_4%Scout%' OR title LIKE '%Llama_4%Maverick%' THEN 'Llama 4 Scout / Maverick'
        ELSE 'Other 2025 AI Architecture Spec'
    END AS model_deployment_profile,
    COUNT(*) AS reported_variants,
    SUM(CAST(score AS INT)) AS aggregate_upvotes,
    AVG(CAST(descendants AS INT)) AS conversation_depth
FROM hackernews
WHERE type IN ('1', '5')
  AND deleted = '0'
  AND (
       title LIKE '%DeepSeek%R_%Distill%_B%'
       OR title LIKE '%DeepSeek%R_%__B%'
       OR title LIKE '%DeepSeek%V_%__B%'
       OR title LIKE '%Llama_3._%_B%GGUF%' OR title LIKE '%Llama_3._%_B%_q_%'
       OR title LIKE '%Llama_3._%_B%Instruct%'
       OR title LIKE '%Llama_4_%_B%Instruct%'
       OR title LIKE '%Qwen_2._%Coder%_B%'
       OR title LIKE '%Qwen_2._%_B%Instruct%'
       OR title LIKE '%Mistral%7B%Instruct%'
       OR title LIKE '%Mixtral%_x%B%Instruct%'
       OR title LIKE '%Phi-_% %B%Instruct%'
       OR title LIKE '%Gemma%_B%Instruct%'
       OR title LIKE '%Command-R%_B%'
       OR title LIKE '%Yi-__%B%Chat%'
       OR title LIKE '%Falcon%_B%Instruct%'
       OR title LIKE '%MPT%_B%Instruct%'
       OR title LIKE '%StarCoder%_B%'
       OR title LIKE '%CodeLlama%_B%Instruct%'
       OR title LIKE '%vicuna%__%b%'
       OR title LIKE '%WizardLM%_B%'
       OR title LIKE '%Orca%__%B%'
       OR title LIKE '%alpaca%__%b%'
       OR title LIKE '%OpenHermes%_B%'
       OR title LIKE '%neural-chat%__%b%'
       OR title LIKE '%Zephyr%_B%'
       OR title LIKE '%SOLAR%__%B%'
       OR title LIKE '%Nous-Hermes%_B%'
       OR title LIKE '%BioMed%_B%'
       OR title LIKE '%Meditron%__%B%'
       OR title LIKE '%Platypus%_B%'
       OR title LIKE '%dolly%__%b%'
       OR title LIKE '%StableLM%_B%'
       OR title LIKE '%RedPajama%_B%'
       OR title LIKE '%OpenLLaMA%_B%'
       OR title LIKE '%TinyLlama%_B%'
       OR title LIKE '%phi-2%'
       OR title LIKE '%Mistral-NeMo%_B%'
       OR title LIKE '%Qwen1.5%_B%Instruct%'
       OR title LIKE '%InternLM%__%B%'
       OR title LIKE '%Baichuan%__%B%'
       OR title LIKE '%ChatGLM%__%B%'
       OR title LIKE '%Aquila%__%B%'
       OR title LIKE '%bloom%__%b%'
       OR title LIKE '%OPT%__%B%'
       OR title LIKE '%GPT-J%_B%'
       OR title LIKE '%pythia%__%b%'
       OR title LIKE '%CausalLM%_B%'
       OR title LIKE '%DeepSeek%Coder%V_%_B%Instruct%'
       OR title LIKE '%Llama_3._%_B%Q4%'
       OR title LIKE '%Llama_3._%_B%Q8%'
       OR title LIKE '%Qwen_2._%Math%_B%'
       OR title LIKE '%Qwen_2._%VL%_B%'
       OR title LIKE '%MiniCPM%_B%'
       OR title LIKE '%SmolLM%_B%'
       OR title LIKE '%Jamba%_B%'
       OR title LIKE '%RWKV%__%B%'
       OR title LIKE '%mamba%__%b%'
       OR title LIKE '%granite%__%b%instruct%'
       OR title LIKE '%Mistral-Large%_B%'
       OR title LIKE '%DeepSeek%V__%_B%'
       OR title LIKE '%Llama_3.3%_B%'
       OR title LIKE '%Qwen3%_B%'
       OR title LIKE '%Gemma_3%_B%Instruct%'
       OR title LIKE '%Llama_4%Scout%' OR title LIKE '%Llama_4%Maverick%'
  )
GROUP BY 1
ORDER BY reported_variants DESC;
